/**
 * FIXED FACE PLACEMENT MAP
 *
 * This file defines the mapping from placement priority (1-40) to geometry face indices.
 *
 * PLACEMENT STRATEGY (Method 12 - Step 8 complete dome):
 * - Priority 1-5: Top pentagon (5 faces touching apex, clockwise from top view)
 * - Priority 6-10: Second ring (5 faces, clockwise)
 * - Priority 11-20: Third ring (10 faces, clockwise)
 * - Priority 21-30: Fourth ring (10 faces, clockwise)
 * - Priority 31-40: Bottom ring (10 faces, clockwise)
 *
 * This mapping was generated by analyzing the actual dome geometry:
 * - Pentagon faces identified by touching apex vertex
 * - Remaining faces grouped by height (Y-coordinate with tolerance 0.15)
 * - Within each level, faces are sorted clockwise by angle (Math.atan2(z, x))
 *
 * This mapping is FIXED and will not change based on dome rotation.
 * To modify placement, regenerate using console-mapping-v2.js script.
 */

/**
 * Maps placement priority (1-based) to geometry face index (0-based).
 *
 * Example: PRIORITY_TO_GEOMETRY[1] = 1 means "Priority 1 item goes to geometry face 1"
 *
 * This array has 41 elements (index 0 is unused, indices 1-40 are the actual mappings)
 */
export const PRIORITY_TO_GEOMETRY: number[] = [
    -1, // Index 0 unused (priorities are 1-based)

    // TOP PENTAGON (5 faces, priorities 1-5)
    0, 1, 2, 3, 4,

    // SECOND RING (5 faces, priorities 6-10)
    5, 6, 7, 8, 9,

    // THIRD RING (10 faces, priorities 11-20)
    10, 11, 12, 13, 14,
    15, 16, 17, 18, 19,

    // FOURTH RING (10 faces, priorities 21-30)
    20, 21, 22, 23, 24,
    25, 26, 27, 28, 29,

    // BOTTOM RING (10 faces, priorities 31-40)
    30, 31, 32, 33, 34,
    35, 36, 37, 38, 39
];

/**
 * Reverse mapping: geometry index → placement priority
 * Auto-generated from PRIORITY_TO_GEOMETRY
 */
export const GEOMETRY_TO_PRIORITY: Map<number, number> = new Map();

// Build reverse map
for (let priority = 1; priority < PRIORITY_TO_GEOMETRY.length; priority++) {
    const geometryIndex = PRIORITY_TO_GEOMETRY[priority];
    if (geometryIndex >= 0) {
        GEOMETRY_TO_PRIORITY.set(geometryIndex, priority);
    }
}

/**
 * Convert from placement priority (from initial-data.json) to geometry index
 * @param priority 1-based priority (1 = highest priority / top face)
 * @returns geometry index (0-based), or null if invalid
 */
export function priorityToGeometryIndex(priority: number): number | null {
    if (priority < 1 || priority >= PRIORITY_TO_GEOMETRY.length) {
        console.error(`Invalid priority: ${priority} (must be 1-${PRIORITY_TO_GEOMETRY.length - 1})`);
        return null;
    }
    const geometryIndex = PRIORITY_TO_GEOMETRY[priority];
    if (geometryIndex < 0) {
        return null;
    }
    return geometryIndex;
}

/**
 * Convert from geometry index to placement priority
 * @param geometryIndex 0-based geometry index
 * @returns placement priority (1-based), or null if not mapped
 */
export function geometryIndexToPriority(geometryIndex: number): number | null {
    return GEOMETRY_TO_PRIORITY.get(geometryIndex) ?? null;
}
